services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bs-api:
    container_name: bs-api
    image: bs/bs:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  bs-ui:
    container_name: bs-ui
    image: bs/bs-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bs-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  bs-api-storage:
    driver: local
